name: shield
description: Shield Fraud SDK Plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: shield_android
      ios:
        default_package: shield_ios

dependencies:
  flutter:
    sdk: flutter
  shield_android:
    path: ../shield_android
  shield_ios:
    path: ../shield_ios
  shield_platform_interface:
    path: ../shield_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
